baseURL = "https://soulcodex.es/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Roberto Garcia - An small blogging place to share programming knowledge"

# i18n configuration
languageCode = "en"
languageName = "English"

# copyright description used only for seo schema
copyright = "Roberto García - soulcodex.es"

enableRobotsTXT = true

# Author config
[author]
    name = "Roberto García"
    email = "info@soulcodex.es"
    link = "mailto:info@soulcodex.es"

[taxonomies]
    series = "series"
    tag = "tags"
    category = "categories"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    name = "Categories"
    url = "/categories/"

[params]
    title = "An small blogging place to share programming knowledge."
    description = "An small blogging place to share programming knowledge and learn from each others."
    images = ["/images/me.webp"]
    [params.header]
        desktopMode = "fixed"
        [params.header.title]
            name = "Roberto García"
            pre = "<i class='fa-solid fa-terminal'></i>&nbsp;"
            typeit = false
    [params.footer]
      enable = true
      custom = "Be always your best version."
      hugo = false
      copyright = true
      author = true
      since = 2023

    [params.section]
      paginate = 10
      dateFormat = "01-02"
      rss = 10

    [params.list]
      paginate = 10
      dateFormat = "01-02"
      rss = 10

    [params.page.share]
        enable = true
        Twitter = true
        Facebook = true
        Linkedin = true
        Whatsapp = false
        Pinterest = false
        Tumblr = false
        HackerNews = false
        Reddit = false
        VK = false
        Buffer = false
        Xing = false
        Line = false
        Instapaper = false
        Pocket = false
        Flipboard = false
        Weibo = false
        Blogger = false
        Baidu = false
        Odnoklassniki = false
        Evernote = false
        Skype = false
        Trello = false
        Mix = false
    [params.search]
        enable = false
        # type of search engine ["lunr", "algolia"]
        type = "lunr"
        # max index length of the chunked content
        contentLength = 4000
        #  max number of results length
        maxResultLength = 10
        #  snippet length of the result
        snippetLength = 30
        #  HTML tag name of the highlight part in results
        highlightTag = "em"
        #  whether to use the absolute URL based on the baseURL in search index
        absoluteURL = false
            [params.search.algolia]
            index = ""
            appID = ""
            searchKey = ""


[Permalinks]
  posts = "/:section/:year/:filename"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false


# Multilingual
# 多语言
[languages]
    [languages.es]
        weight = 2
        languageCode = "es"
        languageName = "Español"
        hasCJKLanguage = true
        [languages.es.menu]
            [[languages.es.menu.main]]
                weight = 1
                identifier = "posts"
                name = "Posts"
                url = "/es/posts/"
                title = ""
            [[languages.es.menu.main]]
                weight = 2
                identifier = "categories"
                name = "Categorías"
                url = "/categories/"
                title = ""
            [[languages.es.menu.main]]
                weight = 3
                identifier = "about"
                name = "Acerca de mí"
                url = "/es/about/"
                title = ""
            [[languages.es.menu.main]]
                weight = 4
                identifier = "github"
                pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
                url = "https://github.com/soulcodex"
                title = "GitHub"
        [languages.es.params]
            [languages.es.params.footer]
                custom = "Se siempre tu mejor version."
            [languages.es.params.home]
                rss = 10
            [languages.es.params.search]
                placeholder = "Buscar ..."
            [languages.es.params.home.profile]
                enable = true
                avatarURL = "/images/me.webp"
                title = "Hola <i class='fa-regular fa-hand fa-xs'></i> soy Roberto Garcia / Backend Software Engineer<br><br><i class='fa-brands fa-php fa-2xl'></i>&nbsp;<i class='fa-brands fa-golang fa-2xl'></i>&nbsp;&nbsp;<i class='fa-brands fa-python fa-2xl'></i>&nbsp;&nbsp;<i class='fa-brands fa-node fa-2xl'></i>"
                subtitle = "Backend Software Engineer en <a target='_blank' href='https://www.linkedin.com/company/wallbox-chargers/'>Wallbox <i class='fa-sharp fa-solid fa-bolt fa-xs' aria-hidden='true'></i></a>"
                typeit = true
                social = true
                disclaimer = "Consejos, tutoriales y experiencias desarrollando software con PHP, Go, Python y Node."
            [languages.es.params.social]
                GitHub = "soulcodex"
                Telegram = "soulcodex"
                Email = "info@soulcodex.es"
                RSS = true
    [languages.en]
        weight = 1
        languageCode = "en"
        languageName = "English"
        hasCJKLanguage = false
        [languages.en.menu]
            [[languages.en.menu.main]]
                weight = 1
                identifier = "posts"
                name = "Posts"
                url = "/posts/"
                title = ""
            [[languages.en.menu.main]]
                weight = 2
                identifier = "categories"
                name = "Categories"
                url = "/categories/"
                title = ""
            [[languages.en.menu.main]]
                weight = 3
                identifier = "about"
                name = "About me"
                url = "/about/"
                title = ""
            [[languages.en.menu.main]]
                weight = 4
                identifier = "github"
                pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
                url = "https://github.com/soulcodex"
                title = "GitHub"
        [languages.en.params]
            [languages.en.params.home]
                rss = 10
            [languages.en.params.search]
                placeholder = "Search ..."
            [languages.en.params.home.profile]
                enable = true
                avatarURL = "/images/me.webp"
                title = "Hello <i class='fa-regular fa-hand fa-xs'></i> I'm Roberto Garcia Backend Software Engineer<br><br><i class='fa-brands fa-php fa-2xl'></i>&nbsp;<i class='fa-brands fa-golang fa-2xl'></i>&nbsp;&nbsp;<i class='fa-brands fa-python fa-2xl'></i>&nbsp;&nbsp;<i class='fa-brands fa-node fa-2xl'></i>"
                subtitle = "Backend Software Engineer at <a target='_blank' href='https://www.linkedin.com/company/wallbox-chargers/'>Wallbox <i class='fa-sharp fa-solid fa-bolt fa-xs' aria-hidden='true'></i></a>"
                typeit = true
                social = true
                disclaimer = "Advices, tutorials and experiences developing software with PHP, Go, Python and Node."
            [languages.en.params.social]
                GitHub = "soulcodex"
                Telegram = "soulcodex"
                Email = "info@soulcodex.es"
                RSS = true