baseURL = "http://example.org/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "RobertGarcia"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"
# language name ["English", "简体中文", "Français", "Polski", ...]
languageName = "English"

# Author config
[author]
  name = "Roberto García"
  email = "info@soulcodex.es"
  link = "mailto:info@soulcodex.es"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""

[params.header]
  [params.header.title]
  name = "Roberto García"
  typeit = true

[params.footer]
  enable = true
  # Custom content (HTML format is supported)
  # 自定义内容 (支持 HTML 格式)
  custom = ""
  hugo = false
  copyright = true
  author = true
  since = 2023

[params.section]
  paginate = 10
  dateFormat = "01-02"
  rss = 10

[params.list]
  paginate = 10
  dateFormat = "01-02"
  rss = 10

[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":year/:filename"

[params.page.share]
  enable = true
  Twitter = true
  Facebook = true
  Linkedin = true
  Whatsapp = false
  Pinterest = false
  Tumblr = false
  HackerNews = false
  Reddit = false
  VK = false
  Buffer = false
  Xing = false
  Line = false
  Instapaper = false
  Pocket = false
  Flipboard = false
  Weibo = false
  Blogger = false
  Baidu = false
  Odnoklassniki = false
  Evernote = false
  Skype = false
  Trello = false
  Mix = false

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false


# Multilingual
# 多语言
[languages]
    [languages.en]
        weight = 1
        languageCode = "en"
        languageName = "English"
        hasCJKLanguage = false
    [languages.en.menu]
        [[languages.en.menu.main]]
            weight = 1
            identifier = "posts"
            pre = ""
            post = ""
            name = "Posts"
            url = "/posts/"
            title = ""
        [[languages.en.menu.main]]
            weight = 2
            identifier = "tags"
            pre = ""
            post = ""
            name = "Tags"
            url = "/tags/"
            title = ""
        [[languages.en.menu.main]]
            weight = 3
            identifier = "categories"
            pre = ""
            post = ""
            name = "Categories"
            url = "/categories/"
            title = ""
        [[languages.en.menu.main]]
            weight = 5
            identifier = "about"
            pre = ""
            post = ""
            name = "About"
            url = "/about/"
            title = ""
        [[languages.en.menu.main]]
            weight = 6
            identifier = "github"
            pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
            post = ""
            name = ""
            url = "https://github.com/dillonzq/LoveIt"
            title = "GitHub"
    [languages.en.params]
        [languages.en.params.home]
            rss = 10
        [languages.en.params.home.profile]
            enable = true
            gravatarEmail = ""
            avatarURL = "/images/avatar.png"
            title = ""
            subtitle = "A Clean, Elegant but Advanced Hugo Theme"
            typeit = true
            social = true
            disclaimer = ""
        [languages.en.params.social]
            GitHub = "xxxx"
            Twitter = "xxxx"
            Instagram = "xxxx"
            Facebook = "xxxx"
            Telegram = "xxxx"
            Youtubelegacy = "xxxx"
            Phone = "555-555-555"
            Email = "xxxx@xxxx.com"
            RSS = true
    [languages.es]
        weight = 2
        languageCode = "es"
        languageName = "Español"
        hasCJKLanguage = true
        copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
        [languages.es.menu]
            [[languages.es.menu.main]]
                weight = 1
                identifier = "posts"
                pre = ""
                post = ""
                name = "Posts"
                url = "/posts/"
                title = ""
            [[languages.es.menu.main]]
                weight = 2
                identifier = "tags"
                pre = ""
                post = ""
                name = "Etiquetas"
                url = "/tags/"
                title = ""
            [[languages.es.menu.main]]
                weight = 3
                identifier = "categories"
                pre = ""
                post = ""
                name = "Categorías"
                url = "/categories/"
                title = ""
            [[languages.es.menu.main]]
                weight = 5
                identifier = "about"
                pre = ""
                post = ""
                name = "Acerca de mí"
                url = "/about/"
                title = ""
            [[languages.es.menu.main]]
                weight = 6
                identifier = "github"
                pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
                post = ""
                name = ""
                url = "https://github.com/dillonzq/LoveIt"
                title = "GitHub"
        [languages.es.params]
            [languages.es.params.home]
                rss = 10
            [languages.es.params.home.profile]
                enable = true
                gravatarEmail = ""
                avatarURL = "/images/avatar.png"
                title = ""
                subtitle = "一个简洁、优雅且高效的 Hugo 主题"
                typeit = true
                social = true
                disclaimer = ""
            [languages.es.params.social]
            GitHub = "xxxx"
            Weibo = "xxxx"
            Steam = "xxxx"
            Zhihu = "xxxx"
            Douban = "xxxx"
            Devto = "xxxx"
            Bilibili = "xxxx"
            Email = "xxxx@xxxx.com"
            Phone = "555-555-555"
            RSS = true
